### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by piresbruno** [hemantasapkota/SwiftStore#2]
When building the project i get:

"building for iOS simulator, but linking in object file built for OSX, for architecture x86_64"

**Comment by piresbruno** [comment]
This might help

"SwiftStore/leveldb/libleveldb.a(write_batch.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64"

**Comment by hemantasapkota** [comment]
Can you update the master now. I've recompiled the leveldb static library. I tested the example project. It's now working fine on the simulator. Let me know if this fixes your problem too. Thanks

**Comment by piresbruno** [comment]
It's working now, thanks @hemantasapkota 
Can you share some light how are you compiling LevelDB to an iOS static library?

**Comment by hemantasapkota** [comment]
Yeah. It's very simple. Download the source from the release link - https://github.com/google/leveldb/releases/tag/v1.18.

Execute the following:
```
make PLATFORM=IOS
```

Cheers
